In [96]:
import pandas as pd
import numpy as np


In [97]:
data = pd.read_csv("play_data.csv")
data

day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [98]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
data['outlook'] = le.fit_transform(data['outlook'])
data['temp'] = le.fit_transform(data['temp'])
data['humidity'] = le.fit_transform(data['humidity'])
data['wind'] = le.fit_transform(data['wind'])
data['play'] = le.fit_transform(data['play'])
data

day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0

In [99]:
x = data[['outlook','temp','humidity','wind']].values
y = data['play'].values

In [100]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest=train_test_split(x, y, test_size=0.3)

In [101]:
data.describe()

outlook       temp   humidity       wind       play
count  14.000000  14.000000  14.000000  14.000000  14.000000
mean    1.071429   1.142857   0.500000   0.571429   0.642857
std     0.828742   0.864438   0.518875   0.513553   0.497245
min     0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.250000   0.250000   0.000000   0.000000   0.000000
50%     1.000000   1.000000   0.500000   1.000000   1.000000
75%     2.000000   2.000000   1.000000   1.000000   1.000000
max     2.000000   2.000000   1.000000   1.000000   1.000000

In [102]:
#xTest = xTest.reshape(1, -1)

In [103]:
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
xTrain = sc.fit_transform(xTrain)  
xTest = sc.transform(xTest)  

In [104]:
#xTrain = xTrain.reshape(-1, 1)

In [117]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()


In [118]:
model.fit(xTrain,yTrain)

GaussianNB()

In [119]:
yPred = model.predict(xTest)
yPred

array([0, 1, 1, 0, 1])

In [120]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, yPred)
cm

array([[1, 0],
       [1, 3]], dtype=int64)

In [121]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(yTest, yPred)*100
acc

80.0

In [126]:
df = pd.DataFrame({'Real Values':yTest, 'Predicted Values':yPred})
df

Real Values  Predicted Values
0            1                 0
1            1                 1
2            1                 1
3            0                 0
4            1                 1

In [131]:
#prepare a model here
myPred =[[0,1,0,1]]
pred = model.predict(myPred)
pred

array([1])

In [133]:
#prepare a model here
myPred =[[2,1,0,0]]
pred = model.predict(myPred)
pred

array([0])