In [20]:
import numpy as np
import pandas as pd


In [21]:
Data = pd.read_table("fruits1.txt")

In [22]:
Data.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [23]:
Data.groupby('fruit_label').size()

fruit_label
1    19
2     5
3    19
4    16
dtype: int64

In [24]:
x = Data[["mass","width","height","color_score"]].values
x

array([[192.  ,   8.4 ,   7.3 ,   0.55],
       [180.  ,   8.  ,   6.8 ,   0.59],
       [176.  ,   7.4 ,   7.2 ,   0.6 ],
       [ 86.  ,   6.2 ,   4.7 ,   0.8 ],
       [ 84.  ,   6.  ,   4.6 ,   0.79],
       [ 80.  ,   5.8 ,   4.3 ,   0.77],
       [ 80.  ,   5.9 ,   4.3 ,   0.81],
       [ 76.  ,   5.8 ,   4.  ,   0.81],
       [178.  ,   7.1 ,   7.8 ,   0.92],
       [172.  ,   7.4 ,   7.  ,   0.89],
       [166.  ,   6.9 ,   7.3 ,   0.93],
       [172.  ,   7.1 ,   7.6 ,   0.92],
       [154.  ,   7.  ,   7.1 ,   0.88],
       [164.  ,   7.3 ,   7.7 ,   0.7 ],
       [152.  ,   7.6 ,   7.3 ,   0.69],
       [156.  ,   7.7 ,   7.1 ,   0.69],
       [156.  ,   7.6 ,   7.5 ,   0.67],
       [168.  ,   7.5 ,   7.6 ,   0.73],
       [162.  ,   7.5 ,   7.1 ,   0.83],
       [162.  ,   7.4 ,   7.2 ,   0.85],
       [160.  ,   7.5 ,   7.5 ,   0.86],
       [156.  ,   7.4 ,   7.4 ,   0.84],
       [140.  ,   7.3 ,   7.1 ,   0.87],
       [170.  ,   7.6 ,   7.9 ,   0.88],
       [342.  , 

In [25]:
y=Data['fruit_label'].values
y

array([1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [27]:
y.shape
y_train.shape

(47,)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [29]:
k = (np.sqrt(len(x_train)))/2
k = round(k)

if k%2 == 0:
  k =k+1
k=int(k)
k  


3

In [30]:
classifier=KNeighborsClassifier(n_neighbors=k)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
#testset = [[5.4, 1.6, 3.4, 2.2]]
y_pred = classifier.predict(x_test)
#y_pred = classifier.predict(testset)
y_pred

array([1, 3, 3, 4, 1, 1, 2, 3, 1, 1, 1, 3], dtype=int64)

In [38]:
y_test

array([1, 4, 1, 4, 1, 4, 2, 3, 1, 1, 4, 1], dtype=int64)

In [33]:
y_pred.shape


(12,)

In [34]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[4, 0, 2, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [2, 0, 1, 1]], dtype=int64)

In [40]:
y_test

array([1, 4, 1, 4, 1, 4, 2, 3, 1, 1, 4, 1], dtype=int64)

In [35]:
acc = accuracy_score(y_test, y_pred)*100
print('ModelAccuracy = '+ str(round(acc,0)))

ModelAccuracy = 58.0


In [36]:
df = pd.DataFrame()
df['Actual Data']= y_test
df['Predicted Data'] = y_pred
df

Actual Data  Predicted Data
0             1               1
1             4               3
2             1               3
3             4               4
4             1               1
5             4               1
6             2               2
7             3               3
8             1               1
9             1               1
10            4               1
11            1               3

In [37]:
# Counting Correct and Wrong 
i = 0
count = 0
wrong = []
for i in range(len(df)):
  if df.iloc[i][0] == df.iloc[i][1]:
    i = i+1
  else:
    wrong.append(i)
#count
wrong

[1, 2, 5, 10, 11]