In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [15]:
Data = pd.read_csv("recruit.csv")
Data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:

le=LabelEncoder()
Data['experience']=le.fit_transform(Data['experience'].astype(str))

In [17]:
Data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           2                    8.0                           9      50000
1           2                    8.0                           6      45000
2           1                    6.0                           7      60000
3           6                   10.0                          10      65000
4           3                    9.0                           6      70000
5           5                    7.0                          10      62000
6           4                    NaN                           7      72000
7           0                    7.0                           8      80000

In [18]:
null_val = ['test_score(out of 10)']
for col in null_val:
    Data[col] = Data[col].replace(0, np.nan)
    mean = int(Data[col].mean(skipna=True))
    Data[col] = Data[col].replace(np.nan, mean)

In [19]:
Data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           2                    8.0                           9      50000
1           2                    8.0                           6      45000
2           1                    6.0                           7      60000
3           6                   10.0                          10      65000
4           3                    9.0                           6      70000
5           5                    7.0                          10      62000
6           4                    7.0                           7      72000
7           0                    7.0                           8      80000

In [29]:
x = Data[['experience','test_score(out of 10)','interview_score(out of 10)']].values
x

array([[ 2.,  8.,  9.],
       [ 2.,  8.,  6.],
       [ 1.,  6.,  7.],
       [ 6., 10., 10.],
       [ 3.,  9.,  6.],
       [ 5.,  7., 10.],
       [ 4.,  7.,  7.],
       [ 0.,  7.,  8.]])

In [30]:
y = Data['salary($)'].values
y

array([50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000],
      dtype=int64)

In [22]:
model = LinearRegression()

In [23]:
model.fit(Data[['experience','test_score(out of 10)','interview_score(out of 10)']],Data['salary($)'])

LinearRegression()

In [24]:
model.predict([[2,9,6]])

array([61195.2906999])