In [99]:
import numpy as np
import pandas as pd


In [100]:
Data= pd.read_csv('Iris.csv')
Data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [101]:
X=Data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']].values
y=Data['Species'].values

In [102]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [104]:
Data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [105]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [106]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [107]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 2, 2, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 2, 1, 1, 2,
       1, 1, 0, 0, 0, 1, 2, 2])

In [108]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 9,  0,  0],
       [ 0,  9,  1],
       [ 0,  1, 10]], dtype=int64)

In [109]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)*100
acc

93.33333333333333

In [110]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values  Predicted Values
0             1                 1
1             1                 1
2             2                 2
3             2                 2
4             0                 0
5             1                 1
6             1                 2
7             0                 0
8             2                 2
9             0                 0
10            2                 2
11            2                 2
12            0                 0
13            0                 0
14            1                 1
15            2                 1
16            2                 2
17            0                 0
18            2                 2
19            1                 1
20            1                 1
21            2                 2
22            1                 1
23            1                 1
24            0                 0
25            0                 0
26            0                 0
27            1                 1
28            2                 2
29            2                 2