In [ ]:
import pandas as pd


In [ ]:
data = pd.read_csv('Salary_Data.csv')
data.head()

In [ ]:
data.info()

In [ ]:
x= data['YearsExperience'].values
y= data['Salary'].values

type(x)


In [ ]:
print(x,'\n\n', y)

In [ ]:
x.shape
y.shape

In [ ]:
x

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [ ]:
# shape of feature should be(no. of samples, no. of features)
x=x.reshape(len(x),1)
print(x)

In [ ]:
# divide data into training and testing samples
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, train_size = 0.80, random_state=1)


In [ ]:
xtrain

In [ ]:
xtest

In [ ]:
ytrain

In [ ]:
ytest

In [ ]:
#prepare model
from sklearn.linear_model import LinearRegression
model = LinearRegression()


In [ ]:
#train model
model.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#prediction
ypred = model.predict(xtest)
ypred

array([75074.50510972, 91873.8056381 , 62008.38247653, 81607.56642631,
       67608.14931932, 89073.92221671])

In [ ]:
ytest

array([83088., 98273., 63218., 93940., 61111., 91738.])

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(ytest, ypred)
r2

0.7616681465472094

In [ ]:
#cross validation
accu = []
for i in range(1, 101):
  xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.80, random_state=i)
  model = LinearRegression()
  model.fit(xtrain, ytrain)
  ypred = model.predict(xtest)
  r2 = r2_score(ytest, ypred)
  accu.append(r2)


In [ ]:
import numpy as np
acc_array = np.array(accu)
acc_array

array([0.76166815, 0.88869567, 0.96950394, 0.95044045, 0.94396286,
       0.93681462, 0.81430228, 0.96311822, 0.93884165, 0.98164235,
       0.94088273, 0.94292692, 0.93944603, 0.96062158, 0.86970124,
       0.79498902, 0.93847448, 0.88643306, 0.94155318, 0.94412991,
       0.93985829, 0.88707026, 0.91841708, 0.9520702 , 0.95317328,
       0.98358497, 0.96364258, 0.92178414, 0.94671727, 0.9944092 ,
       0.89676495, 0.89859957, 0.93507856, 0.92441414, 0.88394765,
       0.95502111, 0.97782421, 0.97247945, 0.99283448, 0.77750835,
       0.98025195, 0.90244618, 0.86880452, 0.93495112, 0.92504879,
       0.97891298, 0.98399194, 0.98027728, 0.94976703, 0.88246796,
       0.96086247, 0.97436467, 0.95011549, 0.949273  , 0.89241371,
       0.98040674, 0.80963515, 0.48152205, 0.95479901, 0.91399254,
       0.95052229, 0.97195098, 0.9582009 , 0.91400678, 0.81127009,
       0.77822856, 0.95888325, 0.97917871, 0.87118241, 0.94293977,
       0.96947922, 0.95627718, 0.98121431, 0.96185917, 0.96522

In [ ]:
acc_array.max()

0.9944092048209745

In [ ]:
acc_array.argmax()

29