In [39]:
import pandas as pd
import numpy as np


In [40]:
data = pd.read_csv("winequality-white",sep=";")
data.tail()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6

In [41]:
data.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [50]:
#x = data[["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]].values
x=np.asarray(data.iloc[:,:-1])
y = data["quality"].values
x

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x=sc.fit(x).transform(x)


In [52]:
from sklearn.model_selection import train_test_split
xTrain,xTest,yTrain,yTest= train_test_split(x,y,train_size=0.2)


In [53]:
from sklearn.naive_bayes import GaussianNB
model= GaussianNB()
model.fit(xTrain,yTrain)


GaussianNB()

In [54]:
yPred =  model.predict(xTest)
yPred

array([7, 6, 7, ..., 6, 6, 5], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(yTest,yPred)
cm

array([[  0,   5,   6,   5,   2,   0,   0],
       [  0,  21,  57,  40,  14,   1,   0],
       [  0,  15, 650, 344, 146,   2,   0],
       [  0,  11, 467, 611, 660,   9,   2],
       [  0,   3,  63, 145, 481,  10,   0],
       [  0,   2,  14,  35,  85,  10,   0],
       [  0,   0,   0,   1,   2,   0,   0]], dtype=int64)

In [56]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(yTest, yPred)*100
acc

45.24113294207706